import Head from 'next/head';
import styles from './Login.module.scss';
import LoginForm from '@/components/LoginForm';

const Login = () => {
  // VARIABLES ----------------
  // CONDITIONS ---------------
  // FUNCTIONS ----------------
  // RETURN -------------------
  return (
    <>
      <Head>
        <title>DefaultPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.Login}>
          <div className={styles.pageHeader}>
            <h1 className={styles.pageTitle}>
              Hello,
            </h1>
            <p className={styles.pageSubtitle}>
              Login to explore more!
            </p>
          </div>
          <div className={styles.pageContent}>
            <LoginForm />
          </div>
        </div>
      </main>
    </>
  );
}

export default Login;