import { useState } from "react";
import Head from "next/head";
import styles from "./Profile.module.scss";
import Navbar from "@/components/Navbar";
import Button from "@/components/Button";
import { LuBookmark, LuMenu, LuPlay, LuSettings } from "react-icons/lu";
import { useRouter } from "next/router";
import CardHero from "@/components/CardHero";
import Menu from "@/components/menu";

const Profile = () => {
  // VARIABLES ----------------
  const user = {
    userName: "Meal hub",
    userImgUrl: "https://gravatar.com/avatar/9d01a5b3fa0a312747df7bc483427ec9?s=400&d=robohash&r=x",
    userBio: "Questa applicazione deve funzionare e deve essere funzionale"
  }
  const router = useRouter();
  // CONDITIONS ---------------
  const [pageTitle, setPageTitle] = useState(user.userName);
  const [pageSubtitle, setPageSubtitle] = useState("Sottotitolo pagina");
  const [isMenuOpen, setMenuOpen] = useState(false);
  const [content, setContent] = useState("saved"); // "saved" |  "watched";
  const [data, setData] = useState(savedData);
  // FUNCTIONS ----------------
  const hendleMenuButton = () => {
    console.log("hendleMenuButton");
    setMenuOpen(!isMenuOpen);
  }
  const handleSwitchContent = (content) => {
    setContent(content);

    setData(content === "saved" ? savedData : watchedData);
  }


  // RETURN -------------------
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Profile}>
        <main>
          {/* ------------ NAVBAR ------------ */}
          <Navbar
            leftButton={
              <Button
                icon={() => <LuMenu size={24} />}
                type="text"
                color="dark"
                onClick={() => hendleMenuButton()}
              />
            }
            pageTitle={pageTitle}
            rightButton={
              <Button
                text=""
                size="xs"
                type="text"
                color="dark"
                icon={() => <LuSettings size={24} />}
              />
            }
          />
          {/* ----------- HEADER ------------- */}
          <div className="page-header">
            <div className={styles.profile__info}>

              <div className={styles.avatar}>
                <img className={styles.avatar__img} src={user.userImgUrl} alt="User image profile" />
              </div>

              <div className={styles.description}>
                <h3>
                  {user.userName}
                </h3>
                <p>
                  {user.userBio}
                </p>
              </div>
            </div>
          </div>

          {/* ------ INIZIO CONTENUTO PAGINA / ELEMENTI DELLA PAGINA ------ */}
          <div className={styles.content}>
            <div className={styles.header}>
              <Button
                text="Saved"
                size="xs"
                type={content === "saved" ? "fill" : "outline"}
                onClick={() => handleSwitchContent("saved")}
                direction={"right"}
                icon={() => <LuBookmark size={18} />}
              />
              <Button
                text="Watched"
                size="xs"
                type={content === "watched" ? "fill" : "outline"}
                onClick={() => handleSwitchContent("watched")}
                direction={"right"}
                icon={() => <LuPlay size={18} />}
              />
            </div>

            <div className={styles.content__content}>
              {data?.map((recep, index) => {
                return (
                  <CardHero data={recep} key={index + "Profile Page"} />
                )
              })}
            </div>
          </div>
          {/* ------ FINE CONTENUTO PAGINA / ELEMENTI DELLA PAGINA ------ */}
        </main>
        {/* --------- MODALS & EXTRAS -------- */}
        <Menu
          isMenuOpen={isMenuOpen}
          setMenuOpen={setMenuOpen}
        />
      </div>
    </>
  );
};

export default Profile;


const savedData = [
  {
    "strMeal": "Baked salmon with fennel & tomatoes",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/1548772327.jpg",
    "idMeal": "52959"
  },
  {
    "strMeal": "Cajun spiced fish tacos",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg",
    "idMeal": "52819"
  },
  {
    "strMeal": "Escovitch Fish",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/1520084413.jpg",
    "idMeal": "52944"
  },
  {
    "strMeal": "Fish fofos",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/a15wsa1614349126.jpg",
    "idMeal": "53043"
  },
  {
    "strMeal": "Fish pie",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/ysxwuq1487323065.jpg",
    "idMeal": "52802"
  },
  {
    "strMeal": "Fish Stew with Rouille",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/vptqpw1511798500.jpg",
    "idMeal": "52918"
  },
  {
    "strMeal": "Garides Saganaki",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/wuvryu1468232995.jpg",
    "idMeal": "52764"
  },
  {
    "strMeal": "Grilled Portuguese sardines",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/lpd4wy1614347943.jpg",
    "idMeal": "53041"
  },
  {
    "strMeal": "Honey Teriyaki Salmon",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg",
    "idMeal": "52773"
  },
  {
    "strMeal": "Kedgeree",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/utxqpt1511639216.jpg",
    "idMeal": "52887"
  },
  {
    "strMeal": "Kung Po Prawns",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/1525873040.jpg",
    "idMeal": "52946"
  },
  {
    "strMeal": "Laksa King Prawn Noodles",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/rvypwy1503069308.jpg",
    "idMeal": "52821"
  },
  {
    "strMeal": "Mediterranean Pasta Salad",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg",
    "idMeal": "52777"
  },
  {
    "strMeal": "Mee goreng mamak",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/xquakq1619787532.jpg",
    "idMeal": "53048"
  },
  {
    "strMeal": "Nasi lemak",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/wai9bw1619788844.jpg",
    "idMeal": "53051"
  },
  {
    "strMeal": "Portuguese fish stew (Caldeirada de peixe)",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/do7zps1614349775.jpg",
    "idMeal": "53045"
  },
  {
    "strMeal": "Recheado Masala Fish",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/uwxusv1487344500.jpg",
    "idMeal": "52809"
  },
  {
    "strMeal": "Salmon Avocado Salad",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/1549542994.jpg",
    "idMeal": "52960"
  },
  {
    "strMeal": "Salmon Prawn Risotto",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/xxrxux1503070723.jpg",
    "idMeal": "52823"
  },
  {
    "strMeal": "Saltfish and Ackee",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/vytypy1511883765.jpg",
    "idMeal": "52936"
  },
  {
    "strMeal": "Seafood fideuà",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/wqqvyq1511179730.jpg",
    "idMeal": "52836"
  },
  {
    "strMeal": "Shrimp Chow Fun",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/1529445434.jpg",
    "idMeal": "52953"
  },
  {
    "strMeal": "Sledz w Oleju (Polish Herrings)",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/7ttta31593350374.jpg",
    "idMeal": "53023"
  },
  {
    "strMeal": "Spring onion and prawn empanadas",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/1c5oso1614347493.jpg",
    "idMeal": "53040"
  },
  {
    "strMeal": "Sushi",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg",
    "idMeal": "53065"
  },
  {
    "strMeal": "Three Fish Pie",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/spswqs1511558697.jpg",
    "idMeal": "52882"
  },
  {
    "strMeal": "Tuna and Egg Briks",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/2dsltq1560461468.jpg",
    "idMeal": "52975"
  },
  {
    "strMeal": "Tuna Nicoise",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/yypwwq1511304979.jpg",
    "idMeal": "52852"
  }

]

const watchedData = [
  {
    "strMeal": "Ayam Percik",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/020z181619788503.jpg",
    "idMeal": "53050"
  },
  {
    "strMeal": "Brown Stew Chicken",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/sypxpx1515365095.jpg",
    "idMeal": "52940"
  },
  {
    "strMeal": "Chick-Fil-A Sandwich",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/sbx7n71587673021.jpg",
    "idMeal": "53016"
  },
  {
    "strMeal": "Chicken & mushroom Hotpot",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/uuuspp1511297945.jpg",
    "idMeal": "52846"
  },
  {
    "strMeal": "Chicken Alfredo Primavera",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg",
    "idMeal": "52796"
  },
  {
    "strMeal": "Chicken Basquaise",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/wruvqv1511880994.jpg",
    "idMeal": "52934"
  },
  {
    "strMeal": "Chicken Congee",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/1529446352.jpg",
    "idMeal": "52956"
  },
  {
    "strMeal": "Chicken Couscous",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/qxytrx1511304021.jpg",
    "idMeal": "52850"
  },
  {
    "strMeal": "Chicken Enchilada Casserole",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/qtuwxu1468233098.jpg",
    "idMeal": "52765"
  },
  {
    "strMeal": "Chicken Fajita Mac and Cheese",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/qrqywr1503066605.jpg",
    "idMeal": "52818"
  },
  {
    "strMeal": "Chicken Ham and Leek Pie",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/xrrtss1511555269.jpg",
    "idMeal": "52875"
  },
  {
    "strMeal": "Chicken Handi",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg",
    "idMeal": "52795"
  },
  {
    "strMeal": "Chicken Karaage",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/tyywsw1505930373.jpg",
    "idMeal": "52831"
  },
  {
    "strMeal": "Chicken Marengo",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/qpxvuq1511798906.jpg",
    "idMeal": "52920"
  },
  {
    "strMeal": "Chicken Parmentier",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/uwvxpv1511557015.jpg",
    "idMeal": "52879"
  },
  {
    "strMeal": "Chicken Quinoa Greek Salad",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/k29viq1585565980.jpg",
    "idMeal": "53011"
  },
  {
    "strMeal": "Coq au vin",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/qstyvs1505931190.jpg",
    "idMeal": "52832"
  },
  {
    "strMeal": "Crock Pot Chicken Baked Tacos",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/ypxvwv1505333929.jpg",
    "idMeal": "52830"
  },
  {
    "strMeal": "French Onion Chicken with Roasted Carrots & Mashed Potatoes",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/b5ft861583188991.jpg",
    "idMeal": "52996"
  },
  {
    "strMeal": "General Tso's Chicken",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/1529444113.jpg",
    "idMeal": "52951"
  },
  {
    "strMeal": "Honey Balsamic Chicken with Crispy Broccoli & Potatoes",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/kvbotn1581012881.jpg",
    "idMeal": "52993"
  },
  {
    "strMeal": "Jerk chicken with rice & peas",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/tytyxu1515363282.jpg",
    "idMeal": "52937"
  },
  {
    "strMeal": "Katsu Chicken curry",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/vwrpps1503068729.jpg",
    "idMeal": "52820"
  },
  {
    "strMeal": "Kentucky Fried Chicken",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/xqusqy1487348868.jpg",
    "idMeal": "52813"
  },
  {
    "strMeal": "Kung Pao Chicken",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/1525872624.jpg",
    "idMeal": "52945"
  },
  {
    "strMeal": "Nutty Chicken Curry",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/yxsurp1511304301.jpg",
    "idMeal": "52851"
  },
  {
    "strMeal": "Pad See Ew",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg",
    "idMeal": "52774"
  },
  {
    "strMeal": "Piri-piri chicken and slaw",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/hglsbl1614346998.jpg",
    "idMeal": "53039"
  },
  {
    "strMeal": "Potato Gratin with Chicken",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/qwrtut1468418027.jpg",
    "idMeal": "52780"
  },
  {
    "strMeal": "Rappie Pie",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/ruwpww1511817242.jpg",
    "idMeal": "52933"
  },
  {
    "strMeal": "Rosół (Polish Chicken Soup)",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/lx1kkj1593349302.jpg",
    "idMeal": "53020"
  },
  {
    "strMeal": "Shawarma",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/kcv6hj1598733479.jpg",
    "idMeal": "53028"
  },
  {
    "strMeal": "Tandoori chicken",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/qptpvt1487339892.jpg",
    "idMeal": "52806"
  },
  {
    "strMeal": "Teriyaki Chicken Casserole",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
    "idMeal": "52772"
  },
  {
    "strMeal": "Thai Green Curry",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/sstssx1487349585.jpg",
    "idMeal": "52814"
  }
]