import styles from './DefaultPage.module.scss';

const DefaultPage = () => {
  // VARIABLES ----------------
  // CONDITIONS ---------------
  // FUNCTIONS ----------------
  // RETURN -------------------
  return (
    <>
      <Head>
        <title>DefaultPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.DefaultPage}>
          <h1>DefaultPage</h1>
        </div>
      </main>
    </>
  );
}

export default DefaultPage;