import Head from "next/head";
import styles from "./Home.module.scss";
import ButtonText from "@/components/ButtonText";
import Button from "@/components/Button";
import { LuAlarmCheck } from "react-icons/lu";
export default function Home() {
  // VARIABLES ----------------
  // CONDITIONS ---------------
  // FUNCTIONS ----------------
  // RETURN -------------------
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Button text={"lol"} icon={<LuAlarmCheck />} /> */}
      <Button text={"lol"} isActive={true} />
      <Button text={"lol"} />
    </>
  );
}
