import Head from 'next/head';
import styles from './Home.module.scss';
import ButtonText from '@/components/ButtonText';



export default function Home() {
  // VARIABLES ----------------
  // CONDITIONS ---------------
  // FUNCTIONS ----------------
  // RETURN -------------------
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.HomePage}>
          <h1 className={styles.title}>Ciao homepage</h1>
          <ButtonText />
        </div>
      </main>
    </>
  )
}
