import { useState } from "react";
import Head from "next/head";
import styles from "./ComunityComments.module.scss";
import Navbar from "@/components/Navbar";
import Button from "@/components/Button";
import { LuMenu, LuUser } from "react-icons/lu";
import { useRouter } from "next/navigation";
import { collection, onSnapshot } from "firebase/firestore";
import { db } from "@/firebase/config";
import { useEffect } from "react";
import CardComments from "@/components/CardComments";
import Menu from "@/components/menu";

const ComunityComments = () => {
  // VARIABLES ----------------
  const router = useRouter();
  // CONDITIONS ---------------
  const [isMenuOpen, setMenuOpen] = useState(false);
  const [pageTitle, setPageTitle] = useState("Comunity Comments");
  const [pageSubtitle, setPageSubtitle] = useState(
    "Here you can fin all comunity comments"
  );

  const [allComments, setAllComments] = useState();
  // FUNCTIONS ----------------
  useEffect(() => {
    onSnapshot(collection(db, "comments"), (docc) => {
      const aux = [];
      docc.forEach((document) => {
        console.log(document.id, " ----- ", document.data());
        const obj = {
          idMeal: document.id,
          comments: document.data().comments,
        };
        aux.push(obj);
      });
      setAllComments(aux);
    });
  }, []);
  // RETURN -------------------
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.HomePage}>
        <main>
          {/* ------------ NAVBAR ------------ */}
          <Navbar
            leftButton={
              <Button
                icon={() => <LuMenu size={24} />}
                type="text"
                color="dark"
                onClick={() => setMenuOpen(!isMenuOpen)}
              />
            }
            pageTitle={pageTitle}
            rightButton={null}
          />
          {/* ----------- HEADER ------------- */}
          <div className="page-header">
            <h1>{pageTitle}</h1>
            <p>{pageSubtitle}</p>
          </div>

          {/* ------ INIZIO CONTENUTO PAGINA / ELEMENTI DELLA PAGINA ------ */}

          <div className={styles.ComunityComments}>
            {allComments?.map((comm, index) => {
              return <CardComments key={"Comunity" + index} data={comm} />;
            })}
          </div>

          {/* ------ FINE CONTENUTO PAGINA / ELEMENTI DELLA PAGINA ------ */}
          <Menu isMenuOpen={isMenuOpen} setMenuOpen={setMenuOpen} />
        </main>
      </div>
    </>
  );
};

export default ComunityComments;
