import { useEffect, useState } from 'react';
import Head from 'next/head';
import styles from './Search.module.scss';
import Navbar from '@/components/Navbar';
import Button from '@/components/Button';
import { LuArrowLeft } from 'react-icons/lu';
import CardGrid from '@/components/cardGrid';
import { getData } from '@/utils/dbManager';
import SearchBar from '@/components/SearchBar';
import { useRouter } from 'next/router';

import { collection, addDoc } from "firebase/firestore";
import { db } from '@/utils/firebase';


const Search = (props) => {
  // VARIABLES ----------------
  const router = useRouter();
  // CONDITIONS ---------------
  const [pageTitle, setPageTitle] = useState(props.title);
  const [data, setData] = useState(props.resp);
  const [isCustom, setIsCustom] = useState(props.isCustom);
  // FUNCTIONS ----------------

  useEffect(() => {
    console.log("asdcs", router.query)
  }, []);

  const doFilter = async () => {
    const filteredData = [];
    const maxCalls = data.length;
    const stepCalls = 5;
    let currentCall = 0;


    const getAllIng = await fetch(
      "https://www.themealdb.com/api/json/v1/1/list.php?a=list"
    );
    const resp = await getAllIng.json();

    console.log(resp.meals);
    const allIng = resp.meals;

    const promises = [];

    const maxCall = 14;
    const step = 14;
    let currentStep = 0;
    let nextStep = currentStep + step;

    const intv = setInterval(async () => {
      for (currentStep; currentStep < nextStep; currentStep++) {

        const docRef = await addDoc(collection(db, "nations"), allIng[currentStep]);
        console.log("Document written with ID: ", docRef.id - " nations : ", allIng[currentStep]);
      }
      if (currentStep === maxCall) clearInterval(intv);
      currentStep = nextStep;
      nextStep = currentStep + step;
    }, 2500);

  }


  const handleGoBack = () => {
    router.back();
  }
  // RETURN -------------------
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Search}>
        <main>
          {/* ------------ NAVBAR ------------ */}
          <Navbar
            leftButton={
              <Button
                icon={() => <LuArrowLeft size={24} />}
                type="text"
                color="dark"
                onClick={() => handleGoBack()}
              />
            }
            pageTitle={pageTitle}
            rightButton={null}
          />
          {/* ----------- HEADER ------------- */}
          <Button
            text="Inizia copiatura"
            onClick={() => doFilter()}
          />
          <div className="page-header">
            <h1>
              {pageTitle} {isCustom ? "true" : " false"}
            </h1>
            <p>
              Total recipes : {data?.length}
            </p>
          </div>

          {/* ----------- SEARCH BAR ------------- */}
          <div className={styles.search__container}>
            <SearchBar />
          </div>

          {/* ------ INIZIO CONTENUTO PAGINA / ELEMENTI DELLA PAGINA ------ */}

          <div className={styles.Search__grid}>
            {
              data?.map((obj, index) => {
                return (
                  <CardGrid data={obj} key={index + "SearchPage"} />
                )
              })
            }
          </div>

          {/* ------ FINE CONTENUTO PAGINA / ELEMENTI DELLA PAGINA ------ */}
        </main>
      </div>
    </>
  );
}

export default Search;

export async function getServerSideProps(context) {
  // VARIABLES ----------------------------
  const query = context.query;
  console.log("------------- context", query);
  let dbResp;


  // FUNCTIONS ----------------------------
  // Resolve query -----------
  const stringQuery = query.id;
  const typeQuery = stringQuery.charAt(0);
  const search = stringQuery.slice(2)
  const promises = [];
  let isCustom = false;
  // Switch call to api based on 
  switch (typeQuery) {
    case "a":
      const dataArea = await getData.area(search);
      dbResp = dataArea.meals;
      break;
    case "c":
      const dataCategory = await getData.category(search);
      dbResp = dataCategory.meals;
      break;

    case "i":
      const dataIngridients = await getData.ingridient(search);
      dbResp = dataIngridients.meals;
      break;

    case "f":
      const dataLetter = await getData.letter(search);
      dbResp = dataLetter.meals;
      break;
    case "k":
      console.log("CUSTOM QUERY : ", stringQuery);

      if (query.nation === "All") {
        console.log("ALL")

        const allNations = await getData.nations();

        for (let i = 0; i < allNations.length; i++) {
          const promise = await getData.area(allNations[i].strArea);
          promises.push(promise.meals);
        }
      }
      const aux = await Promise.all(promises); //this is an Array of Arrays

      let auxOnlyRecipes = [];
      aux.forEach((arr) => {
        auxOnlyRecipes = auxOnlyRecipes.concat(arr);
      })
      isCustom = true;
      dbResp = auxOnlyRecipes;
      break;

    default:
      console.log("Query sbagliata");
      dbResp = []
      break;
  }
  console.log("dbResp : ", dbResp.length)
  // RETURN ----------------------------
  return {
    props: {
      resp: dbResp,
      title: search,
      isCustom: isCustom
    }
  }
}
