import { useState } from "react";
import Head from "next/head";
import styles from "./aboutUs.module.scss";
import Navbar from "@/components/Navbar";
import Button from "@/components/Button";
import { LuMenu, LuUser } from "react-icons/lu";

const ProfileCard = () => {
  // VARIABLES ----------------
  // CONDITIONS ---------------
  const [pageTitle, setPageTitle] = useState("About Us");
  const [pageSubtitle, setPageSubtitle] = useState(
    "Together, this diverse team of Michela, Nina, Luna, and Daniel forms a cohesive unit, combining their respective skills in programming, design, and collaboration. Their collective strengths and collaborative mindset ensure that they can tackle complex projects, finding innovative and elegant solutions to deliver outstanding results in the realm of web development and beyond."
  );

  const profiles = [
    {
      imageSrc: "url_immagine_1.jpg",
      title: "Cerma Michela",
      description:
        "Michela is a highly collaborative team member who always brings an excellent spirit of cooperation to the table. She possesses extensive knowledge and experience in programming with JS, React, and CSS. With her proactive attitude, Michela is always ready to lend a helping hand and find innovative solutions to any challenges the team may encounter.",
    },
    {
      imageSrc: "url_immagine_2.jpg",
      title: "Inchiappa Nina",
      description:
        "Nina is another valuable member of the team, with a unique blend of graphic design skills and expertise in programming with React.jsx and CSS. Her exceptional collaborative abilities make her an asset when working with others, and she excels in problem-solving within the realm of web development.",
    },
    {
      imageSrc: "url_immagine_3.jpg",
      title: "Luna Raimondo",
      description:
        "Luna's strength lies in UI and UX design, bringing a creative and user-centered approach to the team. She has a keen eye for aesthetics and user experience, complemented by her knowledge of programming in JS with the React framework and CSS. Luna's seamless collaboration with her teammates fosters a positive and productive work environment.",
    },
    {
      imageSrc: "url_immagine_3.jpg",
      title: "Turcanu Daniel",
      description:
        "Daniel brings a wealth of knowledge to the team, possessing excellent proficiency in various programming languages such as JS, TypeScript, and a deep understanding of frameworks like React and Next.js. Additionally, he is well-versed in database technologies like MySQL and Firebase. Daniel's broad skillset allows him to tackle a wide range of challenges, and his expertise in different areas makes him a valuable resource for the team.",
    },
  ];
  // FUNCTIONS ----------------
  // RETURN -------------------
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.HomePage}>
        {/* ------------ NAVBAR ------------ */}
        <Navbar
          leftButton={
            <Button
              icon={() => <LuMenu size={24} />}
              type="text"
              color="dark"
            />
          }
          pageTitle={pageTitle}
          rightButton={
            <Button
              icon={() => <LuUser size={24} />}
              type="text"
              color="dark"
            />
          }
        />
        {/* ----------- HEADER ------------- */}
        <main className={styles.main}>
          <div className={styles.title}>
            <h1>{pageTitle}</h1>
            <p>{pageSubtitle}</p>
          </div>

          {/* ------ INIZIO CONTENUTO PAGINA / ELEMENTI DELLA PAGINA ------ */}

          <div className={styles.profile__container}>
            {profiles.map((profile, index) => (
              <div className={styles.profile__card} key={index}>
                <img
                  className={styles.profile__image}
                  src={profile.imageSrc}
                  alt="Profile"
                />
                <div className={styles.text__wrap}>
                  <h2 className={styles.profile__title}>{profile.title}</h2>
                  <p className={styles.profile__description}>
                    {profile.description}
                  </p>
                </div>
              </div>
            ))}
          </div>

          {/* ------ FINE CONTENUTO PAGINA / ELEMENTI DELLA PAGINA ------ */}
        </main>
      </div>
    </>
  );
};

export default ProfileCard;
