import { useState } from 'react';
import Head from 'next/head';
import styles from './SingUp.module.scss';
import Navbar from '@/components/Navbar';
import Button from '@/components/Button';
import { LuMenu, LuUser, LuArrowRight, LuFacebook, LuChrome  } from 'react-icons/lu';

const SingUp = () => {
  // VARIABLES ----------------
  // CONDITIONS ---------------
  const [pageTitle, setPageTitle] = useState("Create an account");
  const [pageSubtitle, setPageSubtitle] = useState("Let’s help you set up your account, it won’t take long.");
  const [name,setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword,setConfirmPassword] = useState("");
  const [isChecked, setIsChecked] = useState(false);
  const [label] = useState("Accept terms and Condition")
  // FUNCTIONS ----------------
  function onSubmit(e) {
    e.preventDefault();
    console.log("Name value" + name);
    console.log("Email value: " + email);
    console.log("Password value: " + password);
    console.log("Confirm Password:" + confirmPassword);
  }
  // RETURN -------------------
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.HomePage}>
        <main>
          {/* ------------ NAVBAR ------------ */}
          <Navbar
            leftButton={
              <Button
                icon={() => <LuMenu size={24} />}
                type="text"
                color="dark"
              />
            }
            pageTitle={pageTitle}
            rightButton={
              <Button
                icon={() => <LuUser size={24} />}
                type="text"
                color="dark"
              />
            }
          />
          {/* ----------- HEADER ------------- */}
          <div className="page-header">
            <h1>
              {pageTitle}
            </h1>
            <p>
              {pageSubtitle}
            </p>
          </div>

          {/* ------ INIZIO CONTENUTO PAGINA / ELEMENTI DELLA PAGINA ------ */}
          
          <form onSubmit={onSubmit} 
           className={styles.container}
          >
            <div>
              <label htmlFor="name">Name</label>
              <input
                className={styles.loginForm}
                type="text"
                name="name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                required
                placeholder="Name"/>
            </div>
            <div>
              <label htmlFor="email">Email</label>
              <input
                className={styles.loginForm}
                type="email"
                name="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
                placeholder="email"/>
            </div>
            <div>
              <label htmlFor="password">Enter Password</label>
              <input
                className={styles.loginForm}
                type="password"
                name="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
                placeholder="Enter Password"
              />
              <label htmlFor="ConfirmPassword">Confirm Password</label>
              <input
                className={styles.loginForm}
                type="Confirm Password"
                name="Confirm Password"
                value={password}
                onChange={(e) => setConfirmPassword(e.target.value)}
                required
                placeholder="Confirm Password"
              />
            </div>
            <div className={styles.checkboxWrapper}>
              <label>
              <input type="checkbox" checked={isChecked} onChange={() => setIsChecked((prev) => !prev)}/>
            <span>{label}</span>
            </label>
            </div>
          <div className={styles.buttonSubmit}>
           <Button 
              icon={() => <LuArrowRight size={24} />}
              size="sm"
              text="Sign in"
              shape="light"
              direction="right"
              submit={true}
              style={{color: 'red', marginTop: 10, padding: 10}}/>
            </div>
            <div className={styles.paragraphContainer}>
            <p className={styles.paragraphSignIn}><span>Or Sign in With</span></p>
            </div>
          </form>
          <div className={styles.socialButton} >
          <Button size="lg" icon={(size) => <LuFacebook size={size} />} />
          <Button size="lg" icon={(size) => <LuChrome size={size} />} />
          </div>
          <p className={styles.paragraph}>Already a member<a className={styles.link} href="sign Up"><span>Sign up</span></a></p>

         

          {/* ------ FINE CONTENUTO PAGINA / ELEMENTI DELLA PAGINA ------ */}
        </main>
      </div>
    </>
  );
}

export default SingUp;